apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
    name: simple-test-pipeline-run
    namespace: tekton-demo
spec:
    pipelineRef:
        name: simple-test-pipeline
    workspaces:
        - name: shared-workspace
          persistentVolumeClaim:
              claimName: tekton-demo-pvc
