apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: tekton-demo-pvc
    namespace: tekton-demo
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
